<?php

namespace app\controllers;

use app\models\Favorite;
use app\models\Fruits;
use app\models\Nutrition;
use Yii;
use yii\data\ActiveDataProvider;
use yii\db\ActiveQuery;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\web\Response;
use yii\helpers\ArrayHelper;

class FruitController extends Controller
{

    /**
     * @throws BadRequestHttpException
     */
    public function beforeAction($action): bool
    {
        \Yii::$app->response->format = Response::FORMAT_JSON;
        if ($action->id == 'my-action') {
            $this->enableCsrfValidation = false;
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     *
     *
     */
    public function actionIndex(): array
    {
        $request = Yii::$app->request;
        $filters = $request->get('filter');

        $data = Fruits::find()->with('nutrition');

        if (!empty($filters['name'])) {
            $data->andWhere(['name' => $filters['name']]);
        }
        if(!empty($filters['family'])){
            $data->andWhere(['family' => $filters['family']]);
        }
        return $this->paginatedResponse($data);
    }

    /**
     * @param ActiveQuery $model
     * @return array
     */
    public function paginatedResponse(ActiveQuery $model): array
    {
        $request = Yii::$app->request;
        $model = new ActiveDataProvider([
            'query' => $model,
            'pagination' => [
                'pageSize' => $request->get('pageSize'),
            ],
//            'sort' => [
//                'defaultOrder' => $request->get('sort')
//                    ? ArrayHelper::map($request->get('sort'), 'field', 'order')
//                    : ['id' => SORT_ASC],
//            ],
        ]);
        return [
            'status' => 200,
            'data' => $model->getModels(),
            'pagination' => [
                'total' => $model->getTotalCount(),
                'page' => $model->getPagination()->getPage() + 1,
                'per_page' => $model->getPagination()->getPageSize(),
                /*'page_count' => $model->getPagination()->getPageCount(),*/
                'page_count' => (int)$request->get('page_count'),
            ],
        ];
    }
    public function actionCreateData()
    {
        $id = Yii::$app->request->post('fruit_id');
        $data = Fruits::find()->where(['id' => $id])->one();

        if($data){
            $favorite = new Favorite();
            $favorite->fruit_id = $data->id;
            $favorite->user_id = random_int(1, 5);
            $favorite->save();

            Yii::$app->response->statusCode = 201;
            return [
                'message' => 'Fruit favorite created successfully',
                'data' => $favorite,
                ];
        }
        else{
            Yii::$app->response->statusCode = 404;
            return ['error' => 'Id does not exist'];
        }
    }

    public function actionGetNutrition()
   {
       $id = Yii::$app->request->get('nutrition_id');
         $data = $data = Fruits::find()->where(['nutrition_id' => $id])->one();
        if($data)
        {
            $nutrition = Nutrition::find()->where(['id' => $data->nutrition_id])->one();
            Yii::$app->response->statusCode = 201;
            return [
                'data' => $nutrition,
            ];
        } else{
            Yii::$app->response->statusCode = 404;
            return ['message' => 'Nutrition id does not exist'];
        }

   }
}
