<?php

namespace app\controllers;

use app\models\Favorite;
use app\models\Fruits;
use app\models\Nutrition;
use Yii;
use yii\data\ActiveDataProvider;
use yii\db\ActiveQuery;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\web\Response;

class FruitController extends Controller
{
    /**
     * @throws BadRequestHttpException
     */
    public function beforeAction($action): bool
    {
        \Yii::$app->response->format = Response::FORMAT_JSON;
        $this->enableCsrfValidation = false;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionIndex(): array
    {
        $request = Yii::$app->request;
        $filters = $request->get('filter');

        $data = Fruits::find()->with('nutrition');

        if (!empty($filters['name'])) {
            $data->andWhere(['like', 'name', $filters['name']]);
        }
        if (!empty($filters['family'])) {
            $data->andWhere(['like', 'family', $filters['family']]);
        }
        return $this->paginatedResponse($data);
    }

    public function paginatedResponse(ActiveQuery $model): array
    {
        $request = Yii::$app->request;
        $model = new ActiveDataProvider([
            'query' => $model,
            'pagination' => [
                'pageSize' => $request->get('pageSize',10),
            ],
        ]);
        return [
            'status' => 200,
            'data' => $model->getModels(),
            'pagination' => [
                'total' => $model->getTotalCount(),
                'page' => $model->getPagination()->getPage() + 1,
                'per_page' => $model->getPagination()->getPageSize(),
                'page_count' => (int)$request->get('page_count'),
            ],
        ];
    }

    public function actionNutrients(): array
    {
        $id = Yii::$app->request->get('fruit_id');
        $data = Fruits::findOne($id);
        if (isset($data)) {
            Yii::$app->response->statusCode = 201;
            return [
                'data' => $data->nutrition,
            ];
        } else {
            Yii::$app->response->statusCode = 404;
            return ['message' => 'Nutrition id does not exist'];
        }

    }
}
